### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [ferromauro/proxy-rotation#1]
Traceback (most recent call last):
  File "C:\Users\andre\OneDrive\Desktop\bot.py", line 33, in <module>
    main()
  File "C:\Users\andre\OneDrive\Desktop\bot.py", line 10, in main
    proxy = next(proxy_pool)
StopIteration

**Comment by ferromauro** [comment]
Sembra che la lista dei proxy sia esaurita e quando ne cerchi si chiamare uno nuovo ti venga restituito questo errore...
Può essere risolto andando ad estrarre una nuova lista di proxy.
